language: node_js
node_js:
- '6'
branches:
  only:
  - master
script:
- npm run generate
- npm run serviceworker
deploy:
  provider: s3
  bucket: brslack.com
  local_dir: public
  region: us-west-2
  skip_cleanup: true
  on:
    branch: master
  access_key_id:
    secure: SCBTRB1lJsxVN8TIzIWFtILkVpbJdFVY9CGzHEWev/UMHs9PNOvEbcyThISFF0qNAjCpJ1vtAl0FqohCGEHojdDWCqXRPtAfKWfwrsdWWaBO23K3VVSBqyOn9alX+BbyugyFBq1WPgSyVyiIIMRwwe8jHWOv4ZWPl2dZ0w+xMjk=
  secret_access_key:
    secure: CVJ6Nm0HKuIm2CU+/sh4bNfYXT/z6gkWbfHOOhuOiDkCh0yOotZ3koNKZY0ILkRZGRWejv2HNHE3ULysuprTTJx5dZYHNqyViUistzt9gz55v7vbS56GuVdUIcUrTJ3b1kls20LYWW/d38biv1xcCHWkgD5eoxIQOur2oQ+e3sE=
